version: '2.1'

services:
  web:
    build: app
    command: python main.py
    depends_on:
      - redis
    restart: always
    env_file:
      - .env

  redis:
    image: "redis:5-alpine"
    command: redis-server --requirepass redis_password --port 6379
    volumes:
      - ./volumes/redis:/data
    env_file:
      - .env